---
- name: HTTPS transport
  apt:
    name: apt-transport-https
    state: present 

- name: Add Docker Repo Key
  apt_key:
    id: 2C52609D
    url: https://apt.dockerproject.org/gpg
    state: present

- name: Add Docker repository and update apt cache
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
    update_cache: yes
    state: present

- name: Install docker-engine package
  apt:
    name: docker-engine
    state: latest
    update_cache: yes

- user:
     name: conductr-agent

- name: Non-root access
  command: usermod -a -G docker conductr-agent
  become: yes
  become_method: sudo

- name: Enable systemd
  command: systemctl enable docker
  become: yes
  become_method: sudo

- name: Copy .dockercfg
  synchronize: src="docker/files/dockercfg" dest="/home/{{ AGENT_USER }}/.dockercfg"

- file: path="/home/{{ AGENT_USER }}/.dockercfg" owner="{{ AGENT_USER }}"

- name: Restart docker
  service:
    name: docker
    state: restarted
  
