---
- command: easy_install pip
  become: yes
  become_method: sudo

- name: Install install
  apt: name=install state=latest

- name: Install build-essential
  apt: name=build-essential state=latest

- name: Install libssl-dev
  apt: name=libssl-dev state=latest

- name: Install libffi-dev
  apt: name=libffi-dev state=latest

- name: Install python-dev
  apt: name=python-dev state=latest

- command: pip install ansible paramiko PyYAML Jinja2 httplib2 boto
  become: yes
  become_method: sudo

- command: pip install ansible paramiko PyYAML Jinja2 httplib2 boto
  become: yes
  become_method: sudo


- command: mkdir -p /etc/ansible
  become: yes
  become_method: sudo

- shell: 'echo -e "[local]\n127.0.0.1" | sudo tee -a /etc/ansible/hosts'
  become: yes
  become_method: sudo
