---
- name: Copy ConductR Agent
  synchronize: src=conductr/files/{{ CONDUCTR_AGENT_PKG }} dest={{ CONDUCTR_CORE_WORK_DIR }}

- name: Install ConductR Agent
  apt: deb={{ CONDUCTR_CORE_WORK_DIR }}/{{ CONDUCTR_AGENT_PKG }}

- command: rm {{ CONDUCTR_CORE_WORK_DIR }}/{{ CONDUCTR_AGENT_PKG }}

- service: name=conductr-agent state=stopped

- shell: 'echo -Dconductr.agent.ip=$(hostname -i)| sudo tee -a /usr/share/conductr-agent/conf/conductr-agent.ini'
  become: yes
  become_method: sudo

- shell: 'echo --core-node {{ CORE_OBSERVER_PRIVATE_IP }}:9004 | sudo tee -a /usr/share/conductr-agent/conf/conductr-agent.ini'
  become: yes
  become_method: sudo

- shell: 'echo -Dakka.loglevel=debug | sudo tee -a /usr/share/conductr-agent/conf/conductr-agent.ini'
  become: yes
  become_method: sudo
  when: "{{ ENABLE_DEBUG }} == true"

- name: Get AZ
  get_url: url=http://169.254.169.254/latest/meta-data/placement/availability-zone dest={{ CONDUCTR_CORE_WORK_DIR }}//az.txt

- shell: "cat {{ CONDUCTR_CORE_WORK_DIR }}/az.txt"
  register: az

- debug:
    var: CONDUCTR_AGENT_ROLES

- shell: 'echo -Dconductr.agent.roles.{{ item.0 }}={{ item.1 }} | sudo tee -a /usr/share/conductr-agent/conf/conductr-agent.ini'
  become: yes
  become_method: sudo
  with_indexed_items: "{{ CONDUCTR_AGENT_ROLES }}"

- shell: 'echo -Dconductr.agent.roles.{{ CONDUCTR_AGENT_ROLES | length }}={{ az.stdout }} | sudo tee -a /usr/share/conductr-agent/conf/conductr-agent.ini'
  become: yes
  become_method: sudo

- service: name=conductr-agent state=started

